
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Pylint
        run: pip install pylint 
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Linter
        run: pylint **/*.py

  data:
    name : Data preparation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Data Preparation
        run: python data_prep.py
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: data-artifacts
          path: |
            X_train.csv
            y_train.csv
            X_test.csv
            y_test.csv

  train:
    name: Train Model
    runs-on: ubuntu-latest
    needs: data
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Download data
        uses: actions/download-artifact@v3
        with:
          name: data-artifacts
          path: .
      - name: Train Model
        run: python train_model.py
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: model-artifacts
          path: |
            linear_regression_model.pkl
            X_test.csv
            y_test.csv

  test:
    name: Test Model
    needs: train 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install scikit-learn pandas joblib
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: model-artifacts
          path: .
      - name: Run Tests
        run: python test_model.py

  deploy:
    name: Deploy Model
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install flask joblib
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: model-artifacts
          path: .
      - name: Deploy Model
        run: python deploy_model.py
